# Spring配置
spring:
  application:
    name: coco-m-server
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://47.109.81.77:16666/coco_music?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: admin
    password: Qaqa123+
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    # redis 配置
    redis:
      # 地址
      host: 47.109.81.77
      # 端口，默认为 6379
      port: 6379
      # 数据库索引
      database: 1
      # 密码
      password: Qaqa123+
      # 连接超时时间
      connect-timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数, 负值表示没有限制，默认8
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制, 默认-1）
          max-wait: -1ms

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

  tomcat:
    # tomcat 的 URI 编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为 100
    accept-count: 1000
    threads:
      # tomcat 最大线程数，默认为 200
      max: 800
      # Tomcat 启动初始化的线程数，默认值 10
      min-spare: 100

mybatis-plus:
  # 配置 mapper 的扫描
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    # 使全局的映射器启用或禁用缓存
    cache-enabled: true
    # 允许 JDBC 支持自动生成主键
    use-generated-keys: true
    # 配置默认的执行器 .SIMPLE 就是普通执行器; REUSE 执行器会重用预处理语句 (prepared statements); BATCH 执行器将重用语句并执行批量更新
    default-executor-type: simple
    # 指定 MyBatis 所用日志的具体实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
  # 搜索指定包别名
  type-aliases-package: com.tangl.music.server.modules.*.entity
  global-config:
    db-config:
      id-type: assign_id
    banner: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.group.coco.server.modules

#swagger:
#  title: coco server 接口文档
#  description: 接口文档，测试用
#  terms-of-service-url: 127.0.0.1:8085
#  contact-name: app
#  contact-url: 127.0.0.1:8085
#  contact-email: app.163.com
#  license-name: app
#  license-url: 127.0.0.1:8085
#  license-identifier: app group
#  version: 1.0

knife4j:
  #  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表