spring:
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:16666/t_music?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /

# 用户配置
user:
  password:
    # 密码最大错误次数
    max-retry-count: 10
    # 密码锁定时间（默认10分钟）
    lock-time: 10

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: N9jPYCXrwkuFIswmhb/VJJ3pHlmK5R3leA6PlDS7XXJv9hftWfuDZD2rfHb1z6qPgIuMx2UvG91/ayBjNskHBg
  # 令牌有效期（默认30分钟）
  expireTime: 30
  iss: tangl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  basic:
    enable: true
